### ISSUE TITLE
User can view a screenshot of the Sway bot in Slack

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/sway-finance#8]
# Motivation 
We want to see the bot in action inside slack so we'll put an image in the page that shows the bot in Slack. 

# Task Implementation
- [ ] Get the Image
- [ ] Get the Dimensions refitted
- [ ] Make sure it's centered 
- [ ] Make sure the margins are correct.
